/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author K-Client
 */
public class ServerGUI extends JFrame {

    Servidor servidor;
    ArrayList<Aeropuerto> vuelos = new ArrayList<>();
    /**
     * Creates new form ServerGUI
     */
    public ServerGUI() {
        initComponents();
        servidor = new Servidor(5000);
        Thread thread = new Thread(servidor);
        thread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        idField = new JTextField();
        salidaField = new JTextField();
        llegadaField = new JTextField();
        updatebtn = new JButton();
        jLabel4 = new JLabel();
        origenField = new JTextField();
        jLabel5 = new JLabel();
        destinoField = new JTextField();
        addbtn = new JButton();
        editbnt = new JButton();
        deletebtn = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Salida");

        jLabel3.setText("Llegada");

        idField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        salidaField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                salidaFieldActionPerformed(evt);
            }
        });

        llegadaField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                llegadaFieldActionPerformed(evt);
            }
        });

        updatebtn.setText("Actualizar Clientes");
        updatebtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Origen");

        origenField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                origenFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Destino");

        destinoField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                destinoFieldActionPerformed(evt);
            }
        });

        addbtn.setText("Add");
        addbtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        editbnt.setText("Edit");
        editbnt.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                editbntActionPerformed(evt);
            }
        });

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updatebtn, GroupLayout.PREFERRED_SIZE, 247, GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(destinoField, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(origenField, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(llegadaField, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE)
                            .addComponent(salidaField, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE)
                            .addComponent(idField, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 97, Short.MAX_VALUE)
                .addComponent(deletebtn, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editbnt, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addbtn, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(salidaField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(llegadaField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(origenField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(destinoField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn)
                    .addComponent(editbnt)
                    .addComponent(deletebtn))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(updatebtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void salidaFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_salidaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salidaFieldActionPerformed

    private void llegadaFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_llegadaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_llegadaFieldActionPerformed

    private void updatebtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        servidor.update(vuelos);
    }//GEN-LAST:event_updatebtnActionPerformed

    private void origenFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_origenFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_origenFieldActionPerformed

    private void destinoFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_destinoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinoFieldActionPerformed

    private void deletebtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        int idDelete = Integer.parseInt(idField.getText());
        for (int i = 0; i < vuelos.size(); i++) {
            Aeropuerto vuelo = vuelos.get(i);
            if (vuelo.getId() == idDelete) {
                vuelos.remove(i);
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "No se puede eliminar el id: " + idDelete);
    }//GEN-LAST:event_deletebtnActionPerformed

    private void editbntActionPerformed(ActionEvent evt) {//GEN-FIRST:event_editbntActionPerformed
        // TODO add your handling code here:
        int idVuelo = 0;
        String origen = "", destino= "", horaSalida= "", horaLlegada= "";
        try {
            idVuelo = Integer.parseInt(idField.getText());
            origen = origenField.getText();
            destino = destinoField.getText();
            horaSalida = salidaField.getText();
            horaLlegada = llegadaField.getText();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El valor del diesel es incorrecto");
        }
        Aeropuerto aeropuertoSend = new Aeropuerto(idVuelo, origen, destino, horaLlegada, horaSalida);
        for (int i = 0; i < vuelos.size(); i++) {
            Aeropuerto vuelo = vuelos.get(i);
            if (vuelo.getId() == idVuelo) {
                vuelos.set(i, aeropuertoSend);
                break;
            }
        }
    }//GEN-LAST:event_editbntActionPerformed

    private void addbtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        int idVuelo = 0;
        String origen = "", destino= "", horaSalida= "", horaLlegada= "";
        try {
            idVuelo = Integer.parseInt(idField.getText());
            for(Aeropuerto vuelo : vuelos) {
                if(vuelo.getId() == idVuelo) {
                    JOptionPane.showMessageDialog(this, "Ya existe un Vuelo con ese ID");
                    return;
                }
            }
            origen = origenField.getText();
            destino = destinoField.getText();
            horaSalida = salidaField.getText();
            horaLlegada = llegadaField.getText();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "E");
        }
        Aeropuerto vueloNuevo = new Aeropuerto(idVuelo, origen, destino, horaLlegada, horaSalida);
        vuelos.add(vueloNuevo);
    }//GEN-LAST:event_addbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ServerGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ServerGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ServerGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ServerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton addbtn;
    private JButton deletebtn;
    private JTextField destinoField;
    private JButton editbnt;
    private JTextField idField;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JTextField llegadaField;
    private JTextField origenField;
    private JTextField salidaField;
    private JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
